# see <https://taskfile.dev/usage/>

version: '3'

vars:
  CRATES_ROOT: "packages/binutils"

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task --list-all

  lint:
    desc: "Run linters"
    cmds:
      - task: lint:clippy
      - task: lint:fmt

  lint:fix:
    desc: "Run lint fixers"
    cmds:
      - task: lint:fix:clippy
      - task: lint:fix:fmt

  ######################################################################## 
  # Silent tasks
  ######################################################################## 

  lint:clippy:
    dir: "{{.CRATES_ROOT}}"
    env:
      RUSTFLAGS: "-D warnings"
    cmds:
      - cargo check --all-targets

  lint:fmt:
    dir: "{{.CRATES_ROOT}}"
    cmds:
      - cargo fmt --check

  lint:fix:clippy:
    dir: "{{.CRATES_ROOT}}"
    cmds:
      - cargo clippy --fix --allow-dirty --allow-staged

  lint:fix:fmt:
    dir: "{{.CRATES_ROOT}}"
    cmds:
      - cargo fmt
