[workspace]
resolver = "2"
members = ["*crates/*"]

[workspace.package]
edition = "2021"
rust-version = "1.80"
license = "MIT"
version = "0.1.0"
authors = ["David J. Hamilton <david@hamilton.gg>"]

[workspace.lints.rust]
unreachable_pub = "warn"


[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[workspace.dependencies]
anyhow = "1.0.89"
cargo_metadata = "0.18.1"
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive"] }
clap_complete = "4.5.29"
config = { git = "https://github.com/malleatus/shared_binutils.git" }
fixturify = { git = "https://github.com/malleatus/shared_binutils.git" }
global = { git = "https://github.com/malleatus/shared_binutils.git" }
insta = { version = "1.36.1", features = ["yaml", "toml"] }
latest_bin = { git = "https://github.com/malleatus/shared_binutils.git" }
lua_config_utils = { git = "https://github.com/malleatus/shared_binutils.git" }
nix = { version = "0.29.0", default-features = false, features = ["process"] }
plist = "1.7.0"
rand = "0.8.5"
regex = "1.10.6"
schemars = "0.8.21"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.122"
shell = { git = "https://github.com/malleatus/shared_binutils.git" }
shellexpand = "3.1.0"
temp-env = "0.3.6"
tempfile = "3.10.1"
test_utils = { git = "https://github.com/malleatus/shared_binutils.git" }
thiserror = "1.0.64"
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
walkdir = "2.5.0"
xdg = "2.5.2"
xml_serde = "1.4.1"
