[package]
name = "binutils"
edition = "2021"
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
cargo_metadata = { workspace = true }
nix = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
walkdir = { workspace = true }
global = { workspace = true }
config = { workspace = true }
latest_bin = { workspace = true }
shell = { workspace = true }
fixturify = { workspace = true }
lua_config_utils = { workspace = true }
regex = { workspace = true }
shellexpand = { workspace = true }
xdg = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
xml_serde = { workspace = true }
plist = { workspace = true }
clap_complete = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
temp-env = { workspace = true }
rand = { workspace = true }
test_utils = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
