# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-0.7.0

      - name: Prepare
        run: |
          test -d build || {
            mkdir -p build
            wget https://github.com/neovim/neovim/releases/download/v0.7.0/nvim.appimage
            chmod +x nvim.appimage
            mv nvim.appimage ./build/nvim
          }

      - name: test
        run: |
          export PATH="${PWD}/build/:${PATH}"
          make -f Makefile.ci test
