# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Download Neovim
        run: |
          mkdir -p build
          wget https://github.com/neovim/neovim/releases/download/v0.7.0/nvim.appimage
          chmod +x nvim.appimage
          mv nvim.appimage ./build/nvim
      - name: Install Plugins
        run: |
          export PATH="${PWD}/build/:${PATH}"
          nvim --headless +'lua require("hjdivad_init").update_plugins()' +quit

      - name: test
        run: |
          export PATH="${PWD}/build/:${PATH}"
          make --version
          make -f Makefile.ci test
