# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"
  workflow_run:
    workflows:
      - "Update Types"
    types:
      - completed

jobs:
  lint:
    env:
      DOTFILES_PATH: "hjdivad/dotfiles"
      BINUTILS_PATH: "hjdivad/dotfiles/packages/binutils"
      SHARED_BINUTILS_PATH: "malleatus/shared_binutils"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.DOTFILES_PATH }}

      - uses: actions/checkout@v4
        with:
          repository: "malleatus/shared_binutils"
          path: ${{ env.SHARED_BINUTILS_PATH }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy

      - name: Setup upterm session
        env:
          DEBUG_SSH: ${{ secrets.DEBUG_SSH }}
        if: ${{ env.DEBUG_SSH == 'true' }}
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          # limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: hjdivad,rwjblue

      # TODO: autoformat is nicer
      - name: cargo fmt
        # uses: actions-rust-lang/rustfmt@v1
        # with:
        #   manifest-path: packages/binutils/Cargo.toml
        run: "cd $BINUTILS_PATH && cargo fmt --check"

      - name: cargo clippy
        run: "cd $BINUTILS_PATH && cargo clippy -- -D warnings"

  test-nvim:
    name: test nvim
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Environment information
        run: |
          uname
          uname -a

      - uses: actions/checkout@v4

      # https://github.com/folke/github/blob/main/neovim/action.yml
      - uses: folke/github/neovim@main

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libreadline-dev

      - name: Test Cache
        uses: actions/cache@v4
        with:
          path: .tests
          key: ${{ runner.os }}-tests-${{ hashFiles('tests/minit.lua', 'scripts/test') }}
      - name: Run Tests
        run: ./scripts/test

      - name: Setup upterm session
        env:
          DEBUG_SSH: ${{ secrets.DebugSSH }}
        if: ${{ env.DEBUG_SSH == 'true' }}
        uses: lhotari/action-upterm@v1
        with:
          # limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          # limits ssh access and adds the ssh public keys of the listed GitHub users
          # limit-access-to-users: hjdivad,rwjblue

  test-binutils:
    name: test binutils
    env:
      DOTFILES_PATH: "hjdivad/dotfiles"
      BINUTILS_PATH: "hjdivad/dotfiles/packages/binutils"
      SHARED_BINUTILS_PATH: "malleatus/shared_binutils"
      RUST_LOG: trace

    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Environment information
        run: |
          uname
          uname -a

      - name: Git Identity Configuration
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - uses: actions/checkout@v4
        with:
          path: ${{ env.DOTFILES_PATH }}

      - uses: actions/checkout@v4
        with:
          repository: "malleatus/shared_binutils"
          path: ${{ env.SHARED_BINUTILS_PATH }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - run: sudo apt-get update && sudo apt-get install -y zsh

      - run: "cd ${{ env.BINUTILS_PATH }} && cargo nextest run --workspace --no-fail-fast"
